### ISSUE TITLE
VIA does not working for aegis in my windows.

### ISSUE THREAD

**Issue by keisuke333** [olivia/via-config#54]
Thank you for adding Aegis to the via-configurator.
But unfortunately it did not work on my windows.
The following screen is displayed for a long time and nothing happens.

<img width="753" alt="via_configurator" src="https://user-images.githubusercontent.com/16768139/54099674-cc9ae180-43fd-11e9-8685-2446e48b45b7.PNG">

**Environment**

Thinkpad T470s
OS: Windows 10 Pro
VIA: v0.2.10
Keyboard: Aegis

**Comment by aeryxz** [comment]
Hey there,
Do you have any other VIA boards you can test with? What length is the usb c cable?
Is the pcb working?

**Comment by keisuke333** [comment]
It worked without problems with my M60-A.
The length of the cable is about 2m.
And my pcb is fine, so I could write firmware using qmk toolbox.

**Comment by keisuke333** [comment]
It didn’t work even with a short cable(1m).
Later I will try via-config with Aegis on mac.

**Comment by Wilba6582** [comment]
If you have built and flashed AEGIS firmware yourself using QMK Toolbox, the firmware may not work with VIA... you have to build the `via` keymap for `aeboards/aegis`

e.g. `make aeboards/aegis:via`

and flash `aeboards_aegis_via.hex`

If you build using `default` keymap as a base, then it will not have the VIA compatibility built into the firmware.

**Comment by keisuke333** [comment]
> If you have built and flashed AEGIS firmware yourself using QMK Toolbox, the firmware may not work with VIA...

Oh, the cause is probably that.
I didn't understand how via-config works. 😢

**Comment by drashna** [comment]
@keisuke333 You just need to flash the VIA keymap in this case. 

Specifically, the features that VIA needs are not enabled in the default keymaps, but in the separate "via" keymap in the QMK FIrmware repo.  
So, if you have the build environment for QMK Firmware setup, you'd just need to run `make aeboards/aegis:via`, and flash the firmware file it creates. 

Otherwise, you'd need to see about getting this firmware from somebody. 

If you need help setting things up, there is a guide for QMK Firmware here: https://docs.qmk.fm/#/newbs

**Comment by keisuke333** [comment]
@aeryxz @Wilba6582 @drashna
It worked well by using the `via` keymap!
Thank you for helping me and sorry I didn't understand the basics.
